### ISSUE TITLE
Phép toán phức tạp

### ISSUE THREAD

**Issue by vuthaihoc** [colombo-trainee/hoannc004#1]
Máy tính bỏ túi ko viết được thế này 😄 
<img width="427" alt="screen shot 2016-05-17 at 16 54 47" src="https://cloud.githubusercontent.com/assets/2509658/15318436/39c6ae70-1c50-11e6-86be-82fa8821d296.png">
của e viết được như cũng ko tính được 😵

**Comment by hoannc54** [comment]
đã sửa về dạng máy tính bỏ túi.
